### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by LamDang** [casami-immo/hackathon#1]
- [x] #2
  - [x] Interface visiteur avec sélection des pièces et jouer la vidéo

- [ ] v2: Interface visiteur avec données manuelles:
  - [x] #4
  - [x] #3
  - [x] #6
  - [x] #5

- [ ] v3: Guide du propriétaire
  - [x] #8
  - [x] #9
  - [ ] Chat pour upload des vidéos en donnant des instructions pour que les vidéos soit bonnes
  - [ ] Vérifications de la qualité des vidéos
  - [ ] Poser des questions par rapport à la vidéo et les sauvegarder dans un FAQ pour plus tard

- [ ] v4: Story telling automatique
  - [ ] Question réponses en contexte de la vidéo (par rapport à la pièce ou arrêt sur un image). 
  - [ ] En fonction de chaque vidéo, proposer au propriétaire un ordre de passage entre les pièces. 

- [ ] v5: Voice chat
  - [ ] Interaction 100% voice avec la vidéo: on est comme dans un facetime. 
  - [ ] Générer l'audio avec ce texte (TTS)
